"""
Sound effects for program feedback.

Uses QSoundEffect (QtMultimedia) to play short tones generated by
tools/generate_sounds.py. If audio is unavailable on the system for any
reason (e.g. no sound card, missing driver), it fails silently -- sound is
an "extra" and must never freeze the program.
"""
from __future__ import annotations

from pathlib import Path

from PySide6.QtCore import QUrl
from PySide6.QtMultimedia import QSoundEffect

SOUNDS_DIR = Path(__file__).resolve().parent.parent / "assets" / "sounds"

_effects: dict[str, QSoundEffect] = {}


def _get_effect(name: str) -> QSoundEffect | None:
    if name in _effects:
        return _effects[name]

    path = SOUNDS_DIR / f"{name}.wav"
    if not path.exists():
        return None

    effect = QSoundEffect()
    effect.setSource(QUrl.fromLocalFile(str(path)))
    effect.setVolume(0.5)
    _effects[name] = effect
    return effect


def play_success() -> None:
    effect = _get_effect("success")
    if effect is not None:
        effect.play()


def play_error() -> None:
    effect = _get_effect("error")
    if effect is not None:
        effect.play()


def play_info() -> None:
    effect = _get_effect("info")
    if effect is not None:
        effect.play()
