"""
Sound effects for program feedback.

Uses QSoundEffect (QtMultimedia) to play short tones generated by
tools/generate_sounds.py. If audio is unavailable on the system for any
reason (e.g. no sound card, missing driver), it fails silently -- sound is
an "extra" and must never freeze the program.
"""
from __future__ import annotations

from pathlib import Path

from PySide6.QtCore import QUrl
from PySide6.QtMultimedia import QSoundEffect

SOUNDS_DIR = Path(__file__).resolve().parent.parent / "assets" / "sounds"

_effects: dict[str, QSoundEffect] = {}
_pending: set[str] = set()


def _get_effect(name: str) -> QSoundEffect | None:
    if name in _effects:
        return _effects[name]

    path = SOUNDS_DIR / f"{name}.wav"
    if not path.exists():
        return None

    effect = QSoundEffect()
    effect.setSource(QUrl.fromLocalFile(str(path)))
    effect.setVolume(0.5)
    _effects[name] = effect
    return effect


def preload() -> None:
    """Create every effect up front so the first play() is not dropped.

    QSoundEffect loads the file asynchronously; a play() call made while the
    effect is still "Loading" is silently ignored. Loading them at startup
    makes them "Ready" long before the first feedback sound is needed.
    """
    for name in ("success", "error", "info"):
        _get_effect(name)


def _play(name: str) -> None:
    effect = _get_effect(name)
    if effect is None:
        return
    if effect.status() == QSoundEffect.Ready:
        effect.play()
        return
    # Still loading: play it as soon as it becomes ready (safety net).
    if name in _pending:
        return
    _pending.add(name)

    def _on_status_changed() -> None:
        if effect.status() == QSoundEffect.Ready:
            _pending.discard(name)
            effect.play()

    effect.statusChanged.connect(_on_status_changed)


def play_success() -> None:
    _play("success")


def play_error() -> None:
    _play("error")


def play_info() -> None:
    _play("info")
